# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# Thunar popups (modales) 
windowrule = float, class:^(thunar)$, title:^Rename.*
windowrule = center, class:^(thunar)$, title:^Rename.*
windowrule = size 342 127, class:^(thunar)$, title:^Rename.*

# Nmtui
windowrule = size 800 900, class:nmtui-popup
windowrule = float, class:nmtui-popup
windowrule = center, class:nmtui-popup

# Bluetooth
windowrule = size 600 450, class:.blueman-manager-wrapped
windowrule = float, class:.blueman-manager-wrapped
windowrule = center,class:.blueman-manager-wrapped

