# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

# idleinhibit
# windowrule = match:class = ([window]), idleinhibit = fullscreen # Available modes: none, always, focus, fullscreen

#xwayland related rules
# when moving objects in resolve a large border is produced 
# This rule prevents that and serves as a template for any problematic xwayland apps
# windowrule = noblur, class:^(\bresolve\b)$, xwayland:1
# This is a general rule for xwayland apps but can have other consequences 
# for one user it impacted EMACs so it's disabled by default 
# It's here as a reference or for quick triage of xwayland ap
#windowrule = noblur, xwayland:1

# Firefox popups (modales)
windowrule = float on, match:class firefox, match:title Library
windowrule = center on, match:class firefox, match:title Library
windowrule = size 981 545, match:class firefox, match:title Library

# Chrome/Chromium/Brave popups (modales)
windowrule = float on, match:class chromium|google-chrome|chrome|Brave-browser, match:modal true
windowrule = center on, match:class chromium|google-chrome|chrome|Brave-browser, match:modal true
windowrule = size 981 545, match:class chromium|google-chrome|chrome|Brave-browser, match:modal true

# Thunar popups (modales)
windowrule = float on, match:class ^(thunar)$, match:title ^Rename.*
windowrule = center on, match:class ^(thunar)$, match:title ^Rename.*
windowrule = size 342 127, match:class ^(thunar)$, match:title ^Rename.*

# xdg-desktop-portal-gtk (Guardar en chrome)
windowrule = float on, match:class xdg-desktop-portal-gtk
windowrule = center on, match:class xdg-desktop-portal-gtk
