#  _   _                  _                 _
# | | | |_   _ _ __  _ __| | __ _ _ __   __| |
# | |_| | | | | '_ \| '__| |/ _` | '_ \ / _` |
# |  _  | |_| | |_) | |  | | (_| | | | | (_| |
# |_| |_|\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
#        |___/|_|
#
# -----------------------------------------------------

# -----------------------------------------------------
# Monitor
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/conf/monitor.conf

# -----------------------------------------------------
# Cursor
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/conf/cursor.conf

# -----------------------------------------------------
# Environment
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/conf/environment.conf

# -----------------------------------------------------
# Keyboard
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/conf/keyboard.conf

# -----------------------------------------------------
# Load color file
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/colors.conf
$primary = $primary
$on_surface = $on_surface

# -----------------------------------------------------
# Autostart
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/conf/autostart.conf

# Create workspace configuration according to number of monitors. Se hace aqui para asegurarnos que se hace a tiempo
exec-once = ~/nixos-dotfiles/config/hypr/scripts/generate-workspace-conf.sh

# -----------------------------------------------------
# Load configuration files
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/conf/window.conf
source = ~/nixos-dotfiles/config/hypr/conf/decoration.conf
source = ~/nixos-dotfiles/config/hypr/conf/layout.conf
source = ~/nixos-dotfiles/config/hypr/conf/workspace.conf
source = ~/nixos-dotfiles/config/hypr/conf/misc.conf
source = ~/nixos-dotfiles/config/hypr/conf/keybinding.conf
source = ~/nixos-dotfiles/config/hypr/conf/windowrule.conf

# -----------------------------------------------------
# Animation
# -----------------------------------------------------
source = ~/nixos-dotfiles/config/hypr/conf/animation.conf

# -----------------------------------------------------
# Environment for xdg-desktop-portal-hyprland
# -----------------------------------------------------
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# -----------------------------------------------------
# Custom
# ----------------------------------------------------- 
source = ~/nixos-dotfiles/config/hypr/conf/custom.conf

exec-once = hyprpaper

exec-once = qs

# Agente necesario para fprintd
exec-once = /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1
