monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.pci-0000_03_00.6.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-on-idle = false
        api.acp.auto-profile = true
        api.acp.auto-port = true
      }
    }
  }
]
